"use client";

import { BundleLanding } from "@/src/components/BundleLanding";

export default function JeeBundle2026Page() {
  return (
    <BundleLanding
      product="jee_bundle_2026"
      price="₹149"
      eyebrow="JEE 2026 exam-cram pack"
      title="10 chapter-wise mocks. Your weak-topic map. ₹149."
      subhead="Ten full-length AI-generated JEE mocks — one per weak chapter, tuned to your diagnostic. Delivered as PDFs within 24 hours. No subscription. No trial games. Just the pack."
      features={[
        "10 chapter-wise JEE Main mock tests (Physics, Chemistry, Maths mixed)",
        "Weak-topic analysis after every mock — you see where to revise",
        "Answer keys with worked solutions, not just letters",
        "Delivered to your inbox within 24 hours",
        "Refund within 3 days if it's not what you expected",
      ]}
      bonusItems={[
        "10 chapter-wise mock test PDFs — each 30 questions, 60 min, JEE Main pattern.",
        "10 detailed solution keys — worked solutions for every question, not just A/B/C/D.",
        "Per-mock weak-topic map — a 1-page report per mock naming the exact concepts you missed.",
        "Optional 15-min WhatsApp doubt call — book once anytime in the next 30 days.",
      ]}
      faqs={[
        {
          q: "Is this AI-generated?",
          a: "Yes. Every mock is generated by our AI, then quality-checked by a JEE tutor before it lands in your inbox. That's the deal that keeps this at ₹149 instead of ₹1,499.",
        },
        {
          q: "Are these full-length JEE Main papers?",
          a: "Chapter-wise 30-question mocks (60 min each). If you want full 3-hour 90-question papers, the Pro subscription (₹199/mo) generates unlimited full-length versions.",
        },
        {
          q: "When will I get the mocks?",
          a: "Within 24 hours of payment. If it's a weekend or a public holiday, it may take up to 48 hours — we'll email you either way.",
        },
        {
          q: "What if I don't like them?",
          a: "Full refund within 3 days, no questions. Reply to the delivery email with 'refund' and we'll process via Razorpay.",
        },
        {
          q: "Can I buy for a friend?",
          a: "Yes. Enter their name and email — they'll get the mocks. Just make sure to WhatsApp us their preferred delivery time if it matters.",
        },
        {
          q: "Do I need to sign up?",
          a: "No account required. This is a one-shot buy — pay, we email, you study.",
        },
      ]}
    />
  );
}
